@startuml Diagramm
struct temperaturePausesStruct{
    byte setpointTemperature[6];
    int16_t time[6];
}
class TRM{
    byte _upButton, _downButton, _numberButton, numberPause = 0, powerMax, powerMin;
    TemperaturePauseCollector collector;
    MyButton settingsButton, startStopButton, motorButton;
    MyThermoCouple termoCouple;
    bool timeSet = false; //переменная связанная со временем, она должна загружаться из EEprom
    TRM(const byte& dwnBtn, const byte& upBtn, const byte& setBtn, const byte& strtBtn,
    const byte& nmbBtn, const byte& mtrBtn, const byte& sckPin, const byte& csPin, const byte& soPin);
    float getTemperature();
    void chooseNumberPause();
    byte getNumberPause() const;
    void enterTemperaturePauses();
    void settings();
    void main();
}
class TemperatureProgramm{
    temperaturePausesStruct _pausesStruct
    TemperatureProgramm(const temperaturePausesStruct& pauses)//создание объекта, хранящего только структуру
    TemperatureProgramm(const int& adress)//создание обекта с ячейкой (чтобы он прочитал прог-му из ячейки)
    Pair<byte, uint16_t> readPause(const byte& pause)//получить паузу из программы
    void writePauses(char temp[6], uint16_t times[6])//записать программу, передав ей массивы(отказ-ся)
    void writePauses(const temperaturePausesStruct& structWrite)//запись программы ч-з стр-ру
    temperaturePausesStruct getPauseAll()//получить программу
    void savePauses(const int& adress)//сохранить программу в ячейку
}

class TemperaturePauseCollector{
    byte _numberProgramms[3] = {0, 1, 2}//номера температурных программ
    int _adress[3]//ячейки в которые будут записываться паузы
    TemperaturePauseCollector()
    void writePauses(const byte& numberProgramm, const temperaturePausesStruct& pause) //запись программы под номером и передача стр-ры в программу
    Pair<byte, uint16_t> readPause(const byte& numberProgramm, const byte& numberPause)//получить одну паузу и программы
    temperaturePausesStruct getPause(const byte& numberProgramm)//получить программу полностью
}

class LCDScreen{

}

struct Koefficients{
    unsigned int P = 0
    unsigned int I = 0
    unsigned int D = 0
}

class PIDRegulator{
    Koefficients koefficients;  //стуктура с коэффициентами
    GyverPID regulator;
    byte _setpointTemperature = 0;  //для указания температуры уставки
    PIDRegulator()  //чтение из EEprom ПИД коэфф-ов и инициализация ПИД регулятора Gyver
    void const setLimits(const byte& minValue, const byte& maxValue) //установка лимитов
    void const putTemperature(const byte& temperature)  //Ввод температуры уставки
    int getValuePID(const float& temperatureIsTermoCouple)  //получение результата после передачи температуры
}



class GyverPID{
    datatype setpoint = 0;     // заданная величина, которую должен поддерживать регулятор
    datatype input = 0;        // сигнал с датчика (например температура, которую мы регулируем)
    datatype output = 0;       // выход с регулятора на управляющее устройство (например величина ШИМ или угол поворота серво)

    datatype getResult();      // возвращает новое значение при вызове (если используем свой таймер с периодом dt!)
    datatype getResultTimer(); // возвращает новое значение не ранее, чем через dt миллисекунд (встроенный таймер с периодом dt)
    void setDirection(boolean direction);    // направление регулирования: NORMAL (0) или REVERSE (1)
    void setMode(boolean mode);              // режим: работа по входной ошибке ON_ERROR (0) или по изменению ON_RATE (1)
    void setLimits(int min_output, int max_output);    // лимит выходной величины (например для ШИМ ставим 0-255)
    void setDt(int16_t new_dt);              // установка времени дискретизации (для getResultTimer)
    float Kp = 0.0;
    float Ki = 0.0;
    float Kd = 0.0;
}

class MyButton{
    byte _pin
    bool _flag = false
    uint32_t _tmr = millis()
    MyButton(byte pin)
    MyButton()
    void ini(byte pin)
    bool click()
    bool pressed()
}

class MyThermoCouple{
    byte _sck, _so, _cs;
    uint8_t spiread(void);
    uint32_t _tmr = millis();
    float temperature = 0;
    MyThermoCouple();
    void ini(byte SCK, byte CS, byte SO);
    float readCelsius();
    float readFarenheit();
}
TRM --* PIDRegulator : Создает
TRM --* temperaturePausesStruct
TemperaturePauseCollector --* temperaturePausesStruct
TemperatureProgramm --* temperaturePausesStruct
PIDRegulator --* Koefficients : Создает из EEprom
PIDRegulator --* GyverPID : Создает для расчетов
TRM--*MyButton : Создает
TRM--*MyThermoCouple : Создает
TRM--*TemperaturePauseCollector: Создает
TemperatureProgramm *--TemperaturePauseCollector:Создает каждый раз при работе с паузами
@enduml