@startuml Settings

class MainMenu{}
class Settings{}
class PauseSettings{}
class WifiSettings{}
class PowerSettings{}
class TimeSettings{}
class TimeDelaySettings{}


MainMenu<--> Settings : SettingsButton.pressed()
Settings <--> PauseSettings : UpButton.click()/ DownButton.click()
PauseSettings <--> WifiSettings : UpButton.click()/ DownButton.click()
WifiSettings <--> PowerSettings : UpButton.click()/ DownButton.click()
PowerSettings <--> TimeSettings : UpButton.click()/ DownButton.click()
TimeSettings <--> TimeDelaySettings : UpButton.click()/ DownButton.click()
@enduml